### ISSUE TITLE
Tag for 16.5.0 missing from repository

### ISSUE THREAD

**Issue by nicoddemus** [mahmoud/boltons#100]
Hi,

The latest boltons release on PyPI is [16.5.0](https://pypi.org/project/boltons/16.5.0/), but this tag is missing from the repository.

**Comment by mahmoud** [comment]
Ah, bitten by the ole `git push --tags`! Time to readd my `git_push` alias that pushes both code and tags. :) Fixed now, thanks for reporting!

**Comment by nicoddemus** [comment]
Cheers 👍

**Comment by jakirkham** [comment]
...or if you are using `git` version 2.x, just run `git config --global push.followTags true` and you can forget about `--tags`. 😉

**Comment by mahmoud** [comment]
@jakirkham better and better! this is what i get for being an early adopter :)
