### ISSUE TITLE
'cachedproperty' decorator replace original's method docstring

### ISSUE THREAD

**Issue by kdeldycke** [mahmoud/boltons#109]
I'm using ``cachedproperty`` a lot as a decorator but the latter seems to replace the original method's docstring by its own.

See for instance that code: https://github.com/kdeldycke/maildir-deduplicate/blob/v2.0.1/maildir_deduplicate/mail.py#L59-L68 . It is rendered by Sphinx with the decorator's docstring instead of the one from the decorated method. See: https://maildir-deduplicate.readthedocs.io/en/stable/maildir_deduplicate.html#maildir_deduplicate.mail.Mail.message

**Comment by induane** [comment]
You might look at the implementation in Django's functional tools. I
believe its cached property decorator preserves the original docstring.

**Comment by induane** [comment]
I added a pull request that should fix the issue:

https://github.com/mahmoud/boltons/pull/110

**Comment by mahmoud** [comment]
My my my, thank you @kdeldycke for the report and @induane for the fix! I've merged and will release shortly. Thanks again, both of you!

**Comment by kdeldycke** [comment]
Wow, that was fast! Thanks @induane and @mahmoud ! :)
