### ISSUE TITLE
Add a PriorityQueue that works with unhashable items?

### ISSUE THREAD

**Issue by pjvandehaar** [mahmoud/boltons#121]
I want to store unhashable things in a priority queue.  For example,

```
from boltons.queueutils import PriorityQueue
q = PriorityQueue()
for i in range(10):
    q.add(dict(a=i), 0)
```

But that produces `TypeError: unhashable type: 'dict'`.

`heapq` won't work either, because if I store tuples `(-priority, item)`, I can get comparisons between `dict`s if priorities match.

Right now I'm using this instead:

```
from boltons.listutils import BList
from bisect import insort

class Heap():
    def __init__(self):
        self._q = BList()
        self._items = {}
        self._idx = 0

    def add(self, item, priority):
        idx = self._idx
        self._idx += 1
        insort(self._q, (-priority, idx))
        self._items[idx] = item

    def pop(self):
        priority, idx = self._q.pop(0)
        return self._items.pop(idx)

    def __len__(self):
        return len(self._q)

    def __iter__(self):
        while self._q:
            yield self.pop()
```

**Comment by tilboerner** [comment]
> heapq won't work either, because if I store tuples `(-priority, item)`, I can get comparisons between dicts if priorities match.

Just a note: As a workaround, it's possible put something that will always compare to False in between: 

```
(-priority, object(), item)
```

The overhead should be manageable in many cases; even unpacking a 3-tuple vs. a 2-tuple in a single assignment seems to take almost the same (very short) time.

**Comment by pjvandehaar** [comment]
Running
```
import heapq
h = []
heapq.heappush?
heapq.heappush(h, (0, object(), 'foo'))
heapq.heappush(h, (0, object(), {1:2}))
```
yields
```
TypeError: '<' not supported between instances of 'object' and 'object'
```
for me.

I wasn't quite clear about the problem.  I want an priority queue where priorities can be repeated *and* items can be unhashable *and* unsortable.

Builtin and `bolton` implementations don't work, because:

* with `boltons.queueutils.PriorityQueue`, items must be hashable (but needn't be sortable).
* with `heapq`, items must be sortable (but needn't be hashable).

**Comment by mahmoud** [comment]
Docs updated, but I would like to think some more about this. I'm not sure there's a way to update priority without a uniqueness constraint, thus one of the original features would be defeated. That said, it has come up in discussion that someone may need a priority queue for non-unique items, but I haven't had any need over the years :)

I'm definitely fine with adding more simple queues, as long as their use case is clear! :)

**Comment by ConorHenry** [comment]
Would float('nan') behave the same as your CmpFalse()? 
Given that:
    >>> float('nan')==float('nan')
    False
    >>> float('nan')<float('nan')
    False
    >>> float('nan')>float('nan')
    False
