### ISSUE TITLE
strip() that works with iterables

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/boltons#122]
I'd like strip / rstrip / lstrip that works with arbitrary iterables:

```python
def iter_lstrip(li, it): 
    pos = 0
    while li[pos] == it:
        pos += 1
        if pos == len(li):
            return []
    return li[pos:]


def iter_rstrip(li, it):
    return list(reversed(iter_lstrip(list(reversed(li)), it)))


def iter_strip(li, it):
    return iter_lstrip(iter_rstrip(li, it), it)
```

```python
iter_strip([0,0,0,1,2,3,4,0,0], 0)
# [1,2,3,4]
```

**Comment by mahmoud** [comment]
Sounds good to me! However, in order to be `iter_` functions, i think they might have to be generators, and maybe there's something to be said for making these work with arbitrary iterables?

**Comment by mblahay** [comment]
I have some code I can modify and then contribute to this. What module should this go into?

@mahmoud, So that I am clear, the criticism with the example provided by @kurtbrose is that it seems to focus on sequences (most probably a list in his example), rather than an arbitrary iterable, correct?

**Comment by kurtbrose** [comment]
yes, basically I'd like to have the same behavior as the string functions strip, rstrip, lstrip that work over arbitrary iterables

maybe there are other string methods which would also be handy (translate?) -- just making the code more cohesive and readable b/c everybody is already familiar with the string methods

**Comment by mblahay** [comment]
Here is an example of iter_lstrip:

`
def iter_lstrip(iterable, value):
    iterator = iter(iterable)
    try:
        #step through the start of iterator, looking for all matching 
        #items that match the value to be stripped
        i = next(iterator)
        while i == value:
            i = next(iterator)

        #yield all remaining items that exist after stripped values
        yield i
        yield from iterator

    #graceful handling of StopIteration within a generator
    except StopIteration:
        pass
`

**Comment by mblahay** [comment]
def iter_lstrip(iterable, strip_value):
        iterator = iter(iterable)
        for i in iterator:
            if i != strip_value: #Check for end of strip_value series
                yield i
                break
        yield from iterator

**Comment by mblahay** [comment]
Here is a function for the right side, but it is admittedly ugly. Suggestions to make it look better are welcome.

    def iter_rstrip(iterable,strip_value):
        iterator = iter(iterable)
        for i in iterator:
            if i == strip_value:
                l = list() #List is used here as a cache
                l.append(i)
                broken = False
                for i in iterator:
                    if i == strip_value:
                        l.append(i)
                    else:
                        broken = True
                        break
                if not broken:
                    return #Return to caller here because the end of the iterator has been reached
                yield from l
            yield i

**Comment by mblahay** [comment]
@kurtbrose, have you see the pull request? @mahmoud  is waiting on your feedback.

**Comment by mblahay** [comment]
@mahmoud , This should be closed.

**Comment by mahmoud** [comment]
Done and done, thanks again!
