### ISSUE TITLE
boltons.fileutils.atomic_save does not allow to save string into the file

### ISSUE THREAD

**Issue by courteouselk** [mahmoud/boltons#131]
If I try to do:

````python
from boltons.fileutils import atomic_save

with atomic_save('test.txt') as f:
    f.write('test')
````

.. then I get an error:

> TypeError: a bytes-like object is required, not 'str'.

What am I doing wrong?  I am using it exactly as decribed in this [answer](https://stackoverflow.com/a/35240362/1542569) at stackoverflow.

**Comment by courteouselk** [comment]
Tried this on both:
- Windows, python 3.6.1, boltons 17.1.0
- Linux, python 3.5.2, boltons 17.1.0

**Comment by mahmoud** [comment]
Hiya! Short version: This is a Python 3 thing, you just need to call `.encode()` on text before you write. This works:

```
from boltons.fileutils import atomic_save

with atomic_save('test.txt') as f:
    f.write('test'.encode('utf8'))
```

Best of luck! :)
