### ISSUE TITLE
setutils.IndexedSet bug

### ISSUE THREAD

**Issue by samegek** [mahmoud/boltons#140]
x = IndexedSet([1,2,3]) | {1,2,3,0,4}
x == IndexedSet([1,2,3,0,4]) # true

it is wrong! the correct answer is {1,2,3,0,4}, it is a set not IndexedSet!
because set is unordered, so  operateing with IndexedSet and  set will only get unorded set!

**Comment by mahmoud** [comment]
Hi @samegek! Thanks for your report! Personally, I think this is a bit of an aesthetic choice, one that matched my use cases for IndexedSet at one point. I should point out that in many cases the ordering is definitely not lost:

```
IndexedSet([1, 2, 3]) | {1, 2}
IndexedSet([1, 2, 3]) | {4}
IndexedSet([1, 2, 3]) | set()
```

So I think this is kind of a practical detail. You can always downconvert an IndexedSet to a normal set to un-order it, too. Does this kind of address your concern?
