### ISSUE TITLE
LRU and LRI yield key errors when max_size reached.

### ISSUE THREAD

**Issue by induane** [mahmoud/boltons#155]
I've created a testcase for the behavior at pull request #154 

When the max size is reached, attempting to set a new key yields a KeyError. I'm not sure why exactly - the error comes from calling ``del self[old]`` - somewhere up the chain this triggers the problem.

**Comment by sp1ky** [comment]
#157

**Comment by mahmoud** [comment]
Thanks for the report! Gonna discuss this over in #157. :)
