### ISSUE TITLE
new iterutils.set_path function

### ISSUE THREAD

**Issue by agdespopoulos** [mahmoud/boltons#163]
Like `get_path`, but for setting. I needed it myself so I wrote a simple version. If this is something you think you'd like added, I can flesh it out with more error handling, documentation, tests, etc.

```python
def set_path(root, path, value):
    """
    Sets a value inside a nested object via a tuple representing the lookup
    path.
    """
    cur = root
    for seg in path[:-1]:
        cur = cur[seg]
    cur[path[-1]] = value
```

**Comment by mahmoud** [comment]
That's great to hear! Unfortunately, I can think of a few cases it won't handle, like tuples.

But there's good news! `get_path` has actually grown into its own package, with much more direction and extensibility: [glom](http://glom.readthedocs.io/en/latest/).

Over in glom, we're working on [assignment](https://github.com/mahmoud/glom/issues/13) as an extension. I'll try to remember to keep this issue updated when we make progress, but I recommend watching that issue, too :) Thanks!

**Comment by mahmoud** [comment]
Here's the aforementioned update: Now that [glom's assign/Assign](https://glom.readthedocs.io/en/latest/api.html#target-mutation-with-assign) has landed, I think it's safe to say that any boltons-scale attempt would struggle to compete. Take a look and let me know what you think! :)
