### ISSUE TITLE
eject arguments (opposite of inject) in wraps

### ISSUE THREAD

**Issue by piccolbo** [mahmoud/boltons#167]
I am a little surprised that one can remove but not add arguments in `wraps`. One may think that the wrapped function has no way to use a new argument that it doesn't know about, but here is a use case. I have a bunch of plotting primitives that take arguments x,y,  and many others, and I want to write a polar coordinates decorators. I need to remove (inject) x and y and replace them with (add) r and t. Then in the decorator body I can compute x and y from r and t and pass them to the decorated function. Makes sense? (of course the name `eject` is a joke. But without renaming `inject`, it's hard to come up with a good name that pairs with the other. Extract?) Thanks

**Comment by mahmoud** [comment]
Well it took me long enough, but I did eventually get around to it! In part thanks to #201.

I must admit, naming was the one of the hardest parts :) I ended up on "expected" as the complement to "injected", as the new wrapper will "expect" those new arguments. 

In any case, it was a good suggestion and I hope the implementation I came up with fits the bill!
