### ISSUE TITLE
An immutable bit-string or bit-array object.

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/boltons#168]
https://gist.github.com/kurtbrose/9d22a0ef0cc5660243bc3ac8dd00cfa1

this is something I've wanted from time to time; basically makes it easy to convert among int, list-of-bools, and '0110' string representations of bit arrays

on PyPI there's some pre-existing work of coursE:

bitarray:  https://pypi.org/project/bitarray/ -- but this adds a binary dependency

bitstring: https://pypi.org/project/bitstring/ -- but it seems to be more focused on packed files / binary structures  (this can probably do the same thing as the example, but you have to dig through a larger API and it is a bigger dependency)

99% of the time I've needed this I couldn't care at all about performance, and I end up doing some little ad-hoc 8 line thing over and over

**Comment by kurtbrose** [comment]
I think I'll break this off and start working on it after complement-set lands; the implementation is pretty strong it could maybe use a few more operator overloads

**Comment by mahmoud** [comment]
This was fixed in #198 :tada: ;)
