### ISSUE TITLE
[ecoutils] PendingDeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5

### ISSUE THREAD

**Issue by villlem** [mahmoud/boltons#169]
Function `ecoutils.get_profile` generates warning since its uses deprecated `platform.linux_distribution()`. 

It would be better to use some replacement like `distro` package (see https://docs.python.org/3.7/library/platform.html#platform.linux_distribution).

It prevents us to simply use `-W error` to find out problems when we update requirements of our project.

**Comment by mahmoud** [comment]
Hmm, well, boltons [do not rely on external packages](https://boltons.readthedocs.io/en/latest/architecture.html#design-of-a-bolton), so using the distro package is out. The good news is that the `platform.linux_distribution()` call is already wrapped in a try/except, so the warning can be safely silenced/ignored. ecoutils will continue to function as-is in 3.8+. :)
