### ISSUE TITLE
Three tests fail when run against CPython nightly 3.8.0a0

### ISSUE THREAD

**Issue by cclauss** [mahmoud/boltons#175]
https://travis-ci.org/mahmoud/boltons/jobs/439532864#L527

**Comment by mahmoud** [comment]
All tests now passing in nightly :) https://travis-ci.org/mahmoud/boltons/jobs/466354390

![screenshot from 2018-12-10 21-56-57](https://user-images.githubusercontent.com/130193/49781158-8b901580-fcc6-11e8-87e9-e364b17d3ba4.png)

Thanks again for this!
