### ISSUE TITLE
boltons.strutils.singularize("chances") returns "chanc"

### ISSUE THREAD

**Issue by orn688** [mahmoud/boltons#188]
To reproduce:
```py
from boltons.strutils import singularize
singularize("chances")  # "chanc"
```

Looking at the `strutils.py` code, it's pretty clear why this happens: `singularize` truncates the last two characters of plural words that end in "es", but not in "ies". It seems to me that most plurals ending in "es" should have just the "s" truncated, but I haven't though super carefully about that. There are definitely a lot of common words that break with this, though ("names", "codes", and "races", to name a few).

**Comment by mahmoud** [comment]
Hey Oliver! Thanks for reporting this. Guess I've just gotten lucky over the years! Not sure what I was thinking with the special case there, but I just now pushed a commit that drops it, per your suggestion. Looked at a dictionary even, definitely seemed like the majority case. Thanks again!
