### ISSUE TITLE
boltons.funcutils.wraps crashes on some docstrings.

### ISSUE THREAD

**Issue by FrozenBob** [mahmoud/boltons#191]
The following example crashes with an IndentationError on boltons 18.0.1:

```
import boltons.funcutils

def deco(f):
  @boltons.funcutils.wraps(f)
  def inner(*args, **kwargs):
    return f(*args, **kwargs)
  return inner

@deco
def f():
  '''
  This docstring includes an example interactive session transcript.
  
  >>> """
  ... Have some pizza.
  ... """
  '''
```

Output:

```
Traceback (most recent call last):
  File "python", line 9, in <module>
  File "python", line 4, in deco
  File "<boltons.funcutils.FunctionBuilder-0>", line 6
    ... Have some pizza.
                       ^
IndentationError: unindent does not match any outer indentation level
```

boltons.funcutils.wraps attempts to string-format the inner function's docstring into the generated wrapper source code, but it does so incorrectly. There doesn't seem to be a point to including the docstring in the generated source anyway, since the docstring gets overwritten by a `__doc__` assignment immediately.

**Comment by mahmoud** [comment]
Hey Bob! That's a good catch and a very good point! Let me see what I can do about that. :)

**Comment by mahmoud** [comment]
Ah, I see why, it always assumes that the original docstring was created with triple double-quotes (`"""`), so docstrings containing those will cause problems.

**Comment by mahmoud** [comment]
Took your suggestion and fixed this right up! Tested working in the commit above. Thanks again!
