### ISSUE TITLE
Priority queue does not support float priorities

### ISSUE THREAD

**Issue by bogdan-kulynych** [mahmoud/boltons#204]
Through a lot of painful debugging in a larger codebase, I found that both of boltons priority queue implementations treat a float priority `p` as if it were `int(p)`.

```
In [1]: from boltons.queueutils import PriorityQueue

In [2]: items = [('a', 0.8), ('b', 0.9), ('c', 0.6), ('d', 1.8), ('e', 1.9), ('f', 1.6)]

In [3]: q = PriorityQueue()

In [4]: for i, p in items: q.add(i, p)

In [5]: for i in range(6): print(q.pop())
d
e
f
a
b
c
```

See the behavior that personally I would expect in this situation, exhibited by a depq package for double-ended priority queues:
```
In [6]: from depq import DEPQ

In [7]: q = DEPQ(items)

In [8]: for i in range(6): print(q.popfirst())
('e', 1.9)
('d', 1.8)
('f', 1.6)
('b', 0.9)
('a', 0.8)
('c', 0.6)
```

I believe the current behavior should be explicitly documented. It's not clear that the priorities would be treated as if they were floored neither from the current docs nor from a brief look at the source.

**Comment by mahmoud** [comment]
Hey Bogdan! I can understand how that could be pretty painful. I checked the docs, and a much younger version of me did happen to mention in the short queueutils docs that the priority key works with integers: [here](https://github.com/mahmoud/boltons/blob/a065dc576c1dc01e9539d973dfb961591ecee427/boltons/queueutils.py#L71).

That said, we can improve the docs or even look at supporting floats, if you're feeling adventurous. :)

**Comment by bogdan-kulynych** [comment]
Thanks for getting back quickly! It seems that only the default priority key had to be changed, so I was feeling adventurous and send the PR :)

**Comment by mahmoud** [comment]
Glad it was straightforward! Is it ok if this waits a bit for the next release?
