### ISSUE TITLE
Flatten is returning dictionary keys

### ISSUE THREAD

**Issue by mattzque** [mahmoud/boltons#207]
I think `iterutils.flatten` would be more useful if it wouldn't do that:

```
>>> from boltons.iterutils import flatten
>>> flatten([[{'a': 1}], [{'b': 2}]])
['a', 'b']
```

More useful would be:
```
>>> from boltons.iterutils import flatten
>>> flatten([[{'a': 1}], [{'b': 2}]])
[{'a': 1}, {'b': 2}]
```

**Comment by mahmoud** [comment]
Hey Matt! Flattening can be a tricky business. the `flatten` in boltons takes a very straightforward approach and just chains all iterables recursively, regardless of type. So for your case, I'd flatten lists of items and construct a new `dict()` myself. 

If you'd like a more dict-aware approach, might I recommend glom's [merge()](https://glom.readthedocs.io/en/latest/api.html#glom.merge)? I built it for just this purpose, and I think you'll find glom has a lot of data manipulation utilities you'll need in the future.

Even though this is a good idea, given there's already code out there assuming this behavior of `iterutils.flatten()`, I'm very reluctant to change it in boltons when I'm already maintaining the next-gen alternative :) Hope it's useful!
