### ISSUE TITLE
Functions for comparing lists

### ISSUE THREAD

**Issue by ponderpanda** [mahmoud/boltons#216]
I have some functions for comparing lists that are similar to the set module but for a group instead of a single instance. An example is list_intersection(a,b) that compares two lists and returns the elements that are in both of them. They are very fast when there is more than one item (a = [1]) being compared so if a or b are close to equal in size or one is above about 500 elements it's faster than the set module tests which are implemented in C if you need the results in a list. It is a pure python module. I created a github account and uploaded for your review. I've never found a similar library and the other methods are thousands of times slower for reasonable data sets. I've used it for comparing directories with millions of files among other things. 

https://github.com/ponderpanda/listex

**Comment by mblahay** [comment]
@ponderpanda, Is your listex repo still around? The link results in a 404 error. Is it possible that it isn't publicly available?

**Comment by mblahay** [comment]
@mahmoud , Should this be closed?

**Comment by mahmoud** [comment]
I suppose so! Thanks for the heads up!
