### ISSUE TITLE
PyPy (PyPy2) breakage on Travis CI

### ISSUE THREAD

**Issue by mahmoud** [mahmoud/boltons#219]
From #218:

> As far as PyPy goes, I'm guessing the new [Travis CI Linux] distro brought a new PyPy, too. That particular error is making itself look like a PyPy bug, but locally, on pypy Python 2.7.13 (7.0.0+dfsg-1~ppa1~ubuntu16.04, Feb 07 2019, 20:56:09), everything's green. So I'll have to handle this out of band, too.
>
> PyPy issue tracked here: https://bitbucket.org/pypy/pypy/issues/3049/systemerror-in-rsocket__setblocking-travis

**Comment by mahmoud** [comment]
Posted to Travis CI support: https://travis-ci.community/t/pypy2-socket-breakage-on-new-default-distro/4549

**Comment by CameronCairns** [comment]
Thoughts on "embracing" microsoft's open source? I can help you move the repo to azure CI if you're interested

**Comment by mahmoud** [comment]
Not a bad thought, but probably the quickest solve here is to pin to a specific version of PyPy, due to an actual PyPy bug I guess I helped find. Azure Pipelines look a bit intense, but if I run into more serious Travis issues, I figure we can port [attrs' configs](https://github.com/python-attrs/attrs/blob/master/azure-pipelines.yml) over.

**Comment by CameronCairns** [comment]
Doesn't have to be super complicated: https://github.com/CameronCairns/django-model-restore/blob/master/azure-pipelines.yml

**Comment by mahmoud** [comment]
Got it taken care of with a quick pytest.mark.xfail. The pypy bug is fixed in 7.2.0, so when travis upgrades, we'll be able to unmark that one pesky test and be back to good. in #226.
