### ISSUE TITLE
update the tox to inlcude python 3.6?

### ISSUE THREAD

**Issue by simkimsia** [mahmoud/boltons#224]
hi there, i discover this library via a SO question and answer. can't believe i have never heard of this library before.

because i am using py 3.6.6 can your tox include that as well?

**Comment by mahmoud** [comment]
Nice! Py3.6 is covered on CI, tox covers 3.4 and 3.7, which pretty much includes everything 3.6 has got to offer. We'll be supporting 3.6 for a good long while, don't worry, import away! :D
