### ISSUE TITLE
`iterutils.get_path` casts strings to ints

### ISSUE THREAD

**Issue by HunterMcGushion** [mahmoud/boltons#227]
First of all, thank you for all your hard work on this excellent library! Also, thank you for making it so easy to include individual modules in projects. `iterutils` has been tremendously useful in my repo, [HyperparameterHunter](https://github.com/HunterMcGushion/hyperparameter_hunter). 

I came across some unexpected behavior in `iterutils.get_path`, where string path elements would be cast to ints. In most cases, this is probably a feature; however, it led to buggy behavior in some admittedly very-edge cases involving deeply nested structures including dicts that could have either string or int keys. It also seems that this type-casting may exist to support the undocumented ability of `get_path` to receive a dotted string `path`, rather than a tuple.

Here’s a snippet to illustrate what seems like inconsistent behavior to me:

```python
assert get_path({0: "foo", "0": "bar"}, (0,)) == "foo"
assert get_path({0: "foo", "0": "bar"}, ("0",)) == "bar"
# Above, we see that `get_path` does correctly differentiate between str/int keys

get_path({0: "foo", "some_other_key": "bar"}, ("0",))  # -> "foo"
# This returns "foo", but I was expecting `PathAccessError` given first two examples
```

In my case, I wasn’t interested in supporting `path` as a string input, so I just removed the try/except block that performed the type casting. If you want to retain support for non-tuple `path` inputs, then conditional type-casting only if `cur` is a list/tuple or if the original input `path` was a string might also do the trick.

Again, I do understand that this is probably a useful feature in some cases and that my case is pretty uncommon, but I think it may be helpful to at least document this behavior. 

If you’re interested in implementing something like my “fix” that removes support for string `path` inputs, I’d be happy to submit a PR, along with some updated tests I put together. Otherwise, if you want to keep everything as-is, I completely understand, so feel free to close this issue. Either way, thank you for your amazing work, and thanks for your time!

**Comment by mahmoud** [comment]
Hi Hunter! Thanks for the kind words. As for the `get_path` issue, I totally agree with you; the majority of the time, I wanted the int-casting behavior (for the string path), but have run into times when I didn't, and I've certainly felt those regrets.

The whole situation drove me to write [glom](https://glom.readthedocs.io/en/latest/), which "just works" but still achieves an explicit behavior, using a registry behind the scenes. I understand if you can't add another dependency (glom's not designed for easy vendoring, but it's pure-python, so it might vendor well), but if you can, give glom a look. Your cases above look to me like they'll work out of the box.

With regards to `iterutils.get_path`, I'm hesitant to change the behavior as some might have come to rely on it, as I have in the past. These days all my applications are switched over to glom, where I think they'll safely be for a very long time :)

**Comment by HunterMcGushion** [comment]
Thanks for the quick response, Mahmoud! I totally understand! I'll close this, so it doesn't clog up your issue tracker. Thanks for recommending glom, as well! I'll definitely be experimenting with it!
