### ISSUE TITLE
Avoid use of __file__

### ISSUE THREAD

**Issue by jayvdb** [mahmoud/boltons#229]
It appears the use of `__file__` here is unnecessary. See indygreg/PyOxidizer#69 for more info about why, but the tl;dr version is `__file__` is an optional attribute and should not be relied upon.

There appears to be only a single use, needed only for the doctest
```py
boltons/fileutils.py:_CUR_DIR = os.path.dirname(os.path.abspath(__file__))
boltons/fileutils.py:    >>> filenames = sorted(iter_find_files(_CUR_DIR, '*.py'))
boltons/fileutils.py:    >>> filenames = iter_find_files(_CUR_DIR, '*.py', ignored='.#*')
```

It could be moved into the doctest's, or alternative doctest which dont need it could achieve the same result.

**Comment by mahmoud** [comment]
You're quite right, of course. `__file__` breaks zip archives. Because it's not really needed for the module functionality, I've moved the `_CUR_DIR` into the test. Thanks for the report!
