### ISSUE TITLE
Importing ABC directly from collections has been removed in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [mahmoud/boltons#236]
Similar to https://github.com/mahmoud/boltons/issues/165 . I will make a PR.

https://github.com/mahmoud/boltons/blob/eefa5ee60461fc16463385f8fcc546a0c1233465/tests/test_dictutils.py#L94

https://github.com/mahmoud/boltons/blob/eefa5ee60461fc16463385f8fcc546a0c1233465/misc/table_html_app.py#L91

**Comment by mahmoud** [comment]
Fixed in your PR, thanks again :)
