### ISSUE TITLE
Signature not updated by wraps()

### ISSUE THREAD

**Issue by aulemahal** [mahmoud/boltons#239]
Hi!
It might be that I don't understand what wraps() is doing but I expected different results:

I did:
```
from inspect import signature
from boltons.funcutils import wraps

def func(a, b=1, c=1):
    print(a, b, c)

newf = wraps(func, injected=['b'])(lambda a, c=1: func(a, b=4, c=c)) 

signature(newf)
```
It returned:
```
<Signature (a, b=1, c=1)>
```
I expected:
```
<Signature (a, c=1)>
```

Is this a bug, or do I not understand  `wraps()`?

I am using boltons 20.0.0 on Python 3.7.3, conda-forge on ArchLinux.

**Comment by mahmoud** [comment]
Hmm, I haven't tested against inspect's signature, we'll need to dig in to figure out what the new approach there is, because `getargspec()` works fine:

```
# continued from the example above
>>> from inspect import getargspec
>>> getargspec(newf)
ArgSpec(args=['a', 'c'], varargs=None, keywords=None, defaults=(1,))
```

**Comment by aulemahal** [comment]
The problem in fact appeared when I was using a jupyter console. In the QtConsole (and elsewhere) a help message appears when you open the parenthesis. They seem to be using `inspect.signature` because it showed me the wrapped function's signature.

**Comment by aulemahal** [comment]
I just realized `signature` has a `follow_wrapped` keyword. When set to `False`, it gives the expected result.

**Comment by mahmoud** [comment]
Oh cool! That's news to me, too! Maybe I should update the docs with a hint on this :) Thanks for letting me know!
