### ISSUE TITLE
singularize("senses") == "sens"

### ISSUE THREAD

**Issue by orn688** [mahmoud/boltons#241]
`strutils.singularize("senses") == "sens"`, but the correct singular is "sense". That's caused by this condition in `singularize`:

```python
elif word.endswith('es') and word[-3] == 's':
    singular = word[:-2]
```

I think "sense" might be irregular, because there are other very similar words for which `singularize()` works correctly, e.g. `singularize("lenses") == "lens"`.

**Comment by mahmoud** [comment]
Hey Oliver! You're quite right. The approach used internally is quite simple, maybe even simplistic! If you'd like to add an exception for senses, I think you'll find the code pretty straightforward to modify, too. Feel free to enhance and I'd gladly take a PR. 

Additionally, there's the `inflect` module which does a much more thorough job of this sort of thing. :)
