### ISSUE TITLE
Unused argument in NetstringSocket

### ISSUE THREAD

**Issue by ikamensh** [mahmoud/boltons#243]
Following line is incorrect and can be confusing:
https://github.com/mahmoud/boltons/blob/9c99fd6e4a345803a43003284cd2aed8a772eb01/boltons/socketutils.py#L640

The value of `maxsize` is never used by this method.

**Comment by ikamensh** [comment]
by the way, do you plan on supporting Python2 in future versions? I could run general cleanup on entire socketutils to update it to Py3 only.

**Comment by mahmoud** [comment]
Good catch! There should be something like `maxsize if maxsize is not _UNSET else self.maxsize` down below. If you'd like to make the PR, feel free.

Py3 is a separate topic, but in general, yes, it's been pretty easy to maintain dual compat, so I plan on continuing boltons py2 support at least through to 2021. Lots of LTS stuff out there, and I prefer not to backport fixes to a py2 branch.

**Comment by ikamensh** [comment]
Ok I have furthermore discovered that timeout argument was not used. Fixed in PR #246 https://github.com/mahmoud/boltons/pull/246

**Comment by mahmoud** [comment]
Merged your #247 which fixes this. Will keep you posted on release to PyPI!
