### ISSUE TITLE
Add support for text mode in boltons.fileutils.atomic_save

### ISSUE THREAD

**Issue by mykter** [mahmoud/boltons#249]
To allow atomic_save to be used as a straight-foward replacement for `open`, it would be nice if it supported a text mode, akin to `open(path, "w")`.
#131 describes a workaround for some situations, but it means atomic_save can't be a drop-in replacement. For example, it can't be easily used with `json.dump`, for which:

> The json module always produces str objects, not bytes objects. Therefore, fp.write() must support str input.

**Comment by mahmoud** [comment]
Ah, it's actually there but not exposed in the docs! Try passing `text_mode=True` and see if that works for you. I'll get it added to the docs asap.

**Comment by mahmoud** [comment]
OK added to the docs now. Good catch, keep an eye out! Thanks!
