### ISSUE TITLE
parse_url throws exception when the password has a #, / or ? in it

### ISSUE THREAD

**Issue by bradmurray** [mahmoud/boltons#251]
parse_url("sftp://username:password#1@ftp.myserver.com:1234/") returns an error because it splits the password at the # character.

**Comment by mahmoud** [comment]
Hey Brad! So, urlutils uses RFC3986's prescribed regex as its basis, and the standard states that `#` is a reserved character in that context and should be encoded.

I'll note that most of my URL-specific efforts have been over here lately: https://github.com/python-hyper/hyperlink/

It's got a different API than urlutils (driven by the fact that its URL objects are immutable), but it also has decent docs: https://hyperlink.readthedocs.io/en/latest/

Using hyperlink we can see the issue:

```python
import hyperlink
base_url = hyperlink.parse(u"sftp://ftp.myserver.com:1234/")
url = base_url.replace(userinfo=(u'username', u'password#1'))
print(url.to_text(with_password=True))
# prints u'sftp://username:password%231@ftp.myserver.com:1234/'
```

And you see the `#` is escaped, per the standard. Hope this helps!
