### ISSUE TITLE
feature request: apply multiple functions to a single argument

### ISSUE THREAD

**Issue by antoine-gallix** [mahmoud/boltons#254]
I've just stumbled across a new use case. I'm parsing the same string with multiple parsers until I get a result. For that I would have combined two iterators I expected to find in `boltons.iterutils` but one does not exist.

It would be like a `map` but instead of applying a function to elements of a collection, producing a collection of results, it would apply a collection of functions to the same argument, also producing a sequence of results.

```python
list(reverse_map([add_two,times_three,is_odd],5))
>>> [7,15,True]
```

With my use case I would do:

```python
token=next(first(reverse_map([parse_token_1,parse_token_2,parse_token_3]),input_string))
```

Would that be interesting to have in `boltons`?

Even though, unless I oversee edge cases, would only be:

```python
def reverse_map(functions, *args, **kwargs):
    for function in functions:
        yield (function(*args, **kwargs))
```

**Comment by mblahay** [comment]
@antoine-gallix, I want to point out that you can use the standard map function to achieve your goal. This ability can be attributed to the fact that you pass functions just as you can any other value. For instance:

    >>> list(map(lambda x:x(5),[add_two,times_three,is_odd]))

    [7, 15, True]

What would the proposed reverse_map bring to the table beyond what can be done with map?

**Comment by antoine-gallix** [comment]
It would bring nothing more than a clearer syntax. If it's not interesting enough, I understand.
