### ISSUE TITLE
MacPorts Installation

### ISSUE THREAD

**Issue by harens** [mahmoud/boltons#264]
As of https://github.com/macports/macports-ports/pull/8302, boltons has been added to MacPorts! This means that it can be installed on macOS by running the following:
```
sudo port install py-boltons
```
(It also has its own MacPorts summary page found [here](https://ports.macports.org/port/py-boltons/summary))

It might be useful to update the docs to show this alternative installation method. I am more than happy to do this and send it as a PR if you want.

**Comment by mahmoud** [comment]
Sure! PR definitely welcome. Do you have a badge you want to add next to conda-forge?

**Comment by harens** [comment]
There's not a badge that I know of, but I can add a custom badge whose version number will need to be updated with each release.

<a href="https://ports.macports.org/port/py-boltons/summary"><img src="https://img.shields.io/badge/macports-v20.2.1-blue?logo=Apple&logoColor=white"></a>

I'll also update the installation instructions in the [README](https://github.com/mahmoud/boltons/blob/master/README.md) and the [docs](https://github.com/mahmoud/boltons/blob/master/docs/index.rst).
