### ISSUE TITLE
python 3.9 test failure version 20.2.1

### ISSUE THREAD

**Issue by ndowens** [mahmoud/boltons#270]
=================================== FAILURES ===================================
_____________________________ test_frozendict_api ______________________________

    def test_frozendict_api():
        # all the read-only methods that are fine
        through_methods = ['__class__',
                           '__cmp__',
                           '__contains__',
                           '__delattr__',
                           '__dir__',
                           '__eq__',
                           '__format__',
                           '__ge__',
                           '__getattribute__',
                           '__getitem__',
                           '__gt__',
                           '__init__',
                           '__iter__',
                           '__le__',
                           '__len__',
                           '__lt__',
                           '__ne__',
                           '__new__',
                           '__reduce__',
                           '__reversed__',
                           '__setattr__',
                           '__sizeof__',
                           '__str__',
                           'copy',
                           'get',
                           'has_key',
                           'items',
                           'iteritems',
                           'iterkeys',
                           'itervalues',
                           'keys',
                           'values',
                           'viewitems',
                           'viewkeys',
                           'viewvalues']
    
        fd = FrozenDict()
        ret = []
        for attrname in dir(fd):
            if attrname == '_hash':  # in the dir, even before it's set
                continue
            attr = getattr(fd, attrname)
            if not callable(attr):
                continue
    
            if getattr(FrozenDict, attrname) == getattr(dict, attrname, None) and attrname not in through_methods:
>               assert attrname == False
E               AssertionError: assert '__ior__' == False

tests/test_dictutils.py:483: AssertionError
=========================== short test summary info ============================
FAILED tests/test_dictutils.py::test_frozendict_api - AssertionError: assert .

**Comment by tirkarthi** [comment]
This is due to Python 3.9 implementing [PEP 584](https://www.python.org/dev/peps/pep-0584/) that adds union of dictionaries through `|` and `|=`. I have created https://github.com/mahmoud/boltons/pull/271 to make sure proper `TypeError` is raised for `|=` but `|` goes through as a fallthrough method.
