### ISSUE TITLE
Insert line of text into exception

### ISSUE THREAD

**Issue by toddrjen** [mahmoud/boltons#28]
One thing I often need to do is to insert an additional line of text into the exception message when handling an exception.  My main use-case for is in loops, particularly in unit tests, where I want to insert additional context information (such as the loop index) to make it easier to track down the source of the exception.  

I also considered the idea of being able to alter the existing message, but I concluded that this is bad programming practice, hence the proposal to only append.

So something like this:

```Python
for i, item in enumerate(mylist):
    try:
        myfunc(item)
    except BaseException:
        AppendMsg('Exception for item %s: %s' % (i, item))
        raise
```

I would be willing to implement this myself, but I want to verify that it would be acceptable before working on it.

**Comment by ekimekim** [comment]
How does this work for exceptions that have a fixed `str()`? eg. if I defined an exception thus:
```python
class MySpecificError(Exception):
    def __str__(self):
        return "This specific error condition occurred"
```
then I don't see how a general function could append something to the end of the message, unless it was wrapping it in a new exception type with a different `__str__` implementation.

**Comment by mahmoud** [comment]
So in the undocumented (and vastly underdeveloped) `excutils` I mention plans for a "MultiException". I have some experiments, but nothing worth sharing yet. Unfortunately, simply adding a line to an exception is insufficient. The args and usage of an Exception type can run a huge gamut; it's not safe to assume strings can contain the main information to be conveyed.

Much like exception chaining in Python 2, MultiExceptions are definitely an idiomatic gap in Python. I'll renew my investigations into MultiException as soon as possible, however. :)
