### ISSUE TITLE
Issue with OrderedMultiDict addlist/popall for empty lists

### ISSUE THREAD

**Issue by radoering** [mahmoud/boltons#284]
We may have encountered an issue when adding an empty list for a key to an OrderedMultiDict (boltons 20.2.1):

```
>>> om = OrderedMultiDict()
>>> om.addlist(1, [])
>>> om.popall(2, None)
>>> om.popall(1, None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "boltons\dictutils.py", line 361, in popall
    self._remove_all(k)
  File "boltons\dictutils.py", line 398, in _remove_all
    values = self._map[k]
KeyError: 1
```

When calling popall for an element with an empty list, an exception is raised instead of returning the default value.

Of course, there is an easy workaround: Just not calling addlist with empty lists. However, addlist or popall should probably be adapted to handle this case.

**Comment by mahmoud** [comment]
That's a good callout, thanks for bringing it up. I've added a test and a fix which should come out in the next release, shortly.
