### ISSUE TITLE
cookbooks code examples are all one liners

### ISSUE THREAD

**Issue by jennifer-klemisch-seagen** [mahmoud/boltons#316]
Hi would you please fix your remap cookbook (https://sedimental.org/remap.html), it looks like this would be so amazingly useful but all the code examples are showing up as one liners. 
--------------------

![image](https://user-images.githubusercontent.com/110173362/193364263-f9e4baaf-4a89-47b1-af91-9ca49cf1b454.png)
----------------
Thank you in advance.

**Comment by mahmoud** [comment]
@jennifer-klemisch-seagen Thanks for the heads up! Behind-the-scenes detail was that I moved machines and my blog had the wrong pygments version or something. Fixed for a couple months now, hope it's helpful!
