### ISSUE TITLE
Include tests in future pypi sdist tarball

### ISSUE THREAD

**Issue by ionenwks** [mahmoud/boltons#329]
Currently tests/ dir is missing, and it's always handy to have to ensure it works in local env and new python versions (forwarded from #328).

Thanks.

**Comment by mahmoud** [comment]
Hey there! Tests are in the latest version, 23.1.0, just released to pypi. 

An odd thing about this was that when I went to implement this, the `MANIFEST.in` already had them included ([here](https://github.com/mahmoud/boltons/blob/b8103e630783d9654033b138e13843a9e363264c/MANIFEST.in#L8)]. So I'm not sure what happened with past releases, maybe a quirk of a build tool version for a previous release? In any case, will keep an eye on this in the future.

**Comment by ionenwks** [comment]
Thanks, still seem to be missing some files though:
```
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/portage/dev-python/boltons-23.1.0/work/boltons
-23.1.0/tests/newlines_test_data.txt'
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/portage/dev-python/boltons-23.1.0/work/boltons
-23.1.0/tests/jsonl_test_data.txt'
```
By diffing the filelists, for the tests/ dir I get (using master given the 23.1.0 tag is missing atm):
```diff
 ./tests
-./tests/.coveragerc
-./tests/__init__.py
-./tests/conftest.py
-./tests/jsonl_test_data.txt
-./tests/newlines_test_data.txt
 ./tests/test_cacheutils.py
 ./tests/test_debugutils_trace.py
 ./tests/test_dictutils.py
```

**Comment by mahmoud** [comment]
Ah, yes, just merged the fix for this in #353, will get it released asap

**Comment by mahmoud** [comment]
Just pushed 23.1.1. The files are now present and a quick check of the pytesting in the untarred sdist seemed to work, let me know how it works for ya!

**Comment by ionenwks** [comment]
Thanks, indeed works fine now.
