### ISSUE TITLE
iterutils.get_path has undocumented path as string parameter

### ISSUE THREAD

**Issue by phnmn** [mahmoud/boltons#363]
A was able to pass the dotted string as the path and it would be split into
``` 
 if isinstance(path, basestring):
        path = path.split('.')
```
but the ability to pass a string to the get_path function is not documented

**Comment by shahzaib512** [comment]
def get_path(path):
    """
    Returns the path by splitting the dotted string.
    
    Parameters:
    path (str): A dotted string representing the path.
    
    Returns:
    list: List of path components.
    """
    if isinstance(path, str):
        path = path.split('.')
    return path
