### ISSUE TITLE
PermissionError with AtomicSaver on Windows

### ISSUE THREAD

**Issue by MrLeeh** [mahmoud/boltons#45]
If I try this little code on Windows 7:
```python
from boltons.fileutils import AtomicSaver
with AtomicSaver('foo.txt') as f:
    f.write('whatever')
```
I get the following Exception:
```bash
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\boltons\fileutils.py", line 272, in setup
    overwrite=self.overwrite_part)
  File "C:\Python34\lib\site-packages\boltons\fileutils.py", line 194, in _atomic_rename
    os.rename(path, new_path)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem ande
ren Prozess verwendet wird: 'C:\\Windows\\System32\\tmphia0tzzm' -> 'foo.txt.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\boltons\fileutils.py", line 281, in __enter__
    self.setup()
  File "C:\Python34\lib\site-packages\boltons\fileutils.py", line 274, in setup
    os.unlink(tmp_part_path)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem ande
ren Prozess verwendet wird: 'C:\\Windows\\System32\\tmphia0tzzm'
```

**Comment by mahmoud** [comment]
Interesting, looks like a Windows file locking issue? I'll have to dust off my Windows machine and give it a closer look. I bet it affects all versions of Windows, but just in case, is this Windows 7 or?

**Comment by MrLeeh** [comment]
Yes it' s Windows 7...

**Comment by mahmoud** [comment]
Hey MrLeeh, give it another shot, seems to work great for me on Windows 7 (and Unix).

**Comment by MrLeeh** [comment]
That is strange. For me it is still not working. Actually I discovered the buck when using the *pip-tools* library which uses the *AtomicSaver*.

**Comment by mahmoud** [comment]
Interesting. Does that mean you're using the pip installed boltons or are you working off the git trunk, or easiest probably, just downloading [fileutils.py](https://raw.githubusercontent.com/mahmoud/boltons/master/boltons/fileutils.py) and importing it?

**Comment by MrLeeh** [comment]
Currently I' m using the pip install boltons (0.6.5)

**Comment by mahmoud** [comment]
Ah, yes, the PyPI version hasn't been updated yet. To test the fix just run `pip install -e git+https://github.com/mahmoud/boltons.git#egg=boltons` and try the fileutils code in question. Or, if you'd like, I can roll out 0.6.6 and you can test that (I did test on Windows 7 earlier today ;) )

**Comment by MrLeeh** [comment]
Thanks for the link. Now I don' t get this error anymore. But another one:

```python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from boltons.fileutils import AtomicSaver
>>> with AtomicSaver('foo.txt') as f:
...     f.write('whatever')
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: 'str' does not support the buffer interface
```
Am I doing something wrong by passing just the String to the write function?

**Comment by mahmoud** [comment]
Ah, Python 3. You need to encode that string to bytes before writing. `f.write('mystring'.encode('utf8'))` OR `f.write(b'mystring')`.

**Comment by MrLeeh** [comment]
Ah, great. That works nice now. I didn' t think about byte encoding. Thank you very much for your help here :+1:

**Comment by mahmoud** [comment]
no problem, enjoy!
