### ISSUE TITLE
Return a pair from boltons.iterutils.bucketize

### ISSUE THREAD

**Issue by dan-passaro** [mahmoud/boltons#50]
**EDIT**: nevermind, just read the docs for `partition`. Derp

Hey there,

Reading the docs of this lib and wondering why not return a pair from `bucketize`?

Current behavior:

    >>> bucketize(range(5))
    {False: [0], True: [1, 2, 3, 4]}
    >>> is_odd = lambda x: x % 2 == 1
    >>> bucketize(range(5), is_odd)
    {False: [0, 2, 4], True: [1, 3]}

Instead:

    >>> bucketize(range(5))
    {False: [0], True: [1, 2, 3, 4]}
    >>> is_odd = lambda x: x % 2 == 1
    >>> bucketize(range(5), is_odd)
    ([0, 2, 4], [1, 3])

I feel this will make client code more straightforward.

    >>> groups = bucektize(range(5), is_odd)
    >>> even_nums = groups[False]
    >>> odd_nums = groups[True]

vs.

    >>> even_nums, odd_nums = bucketize(range(5), is_odd)

Thoughts?

**Comment by mahmoud** [comment]
Hehehe, great minds think and derp alike, thanks for reading the docs! :)

**Comment by mahmoud** [comment]
Maybe I should make the example more clear: bucketize is mostly useful for non-binary bucketization. For instance, grouping a list of tuples into a dictionary that indexes them by length.
