### ISSUE TITLE
Adding entry to LRU cache fails with KeyError

### ISSUE THREAD

**Issue by mt** [mahmoud/boltons#55]
For certain sequences of key insertions, a KeyError is produced in the LRU

For example: 
```python
def produce_key_error():
    from boltons.cacheutils import LRU
    cache = LRU(max_size=3)
    
    keys = ['A', 'A', 'B', 'A', 'C', 'B', 'D', 'E']
    for k in keys:
        cache[k] = 'HIT'
```

**Comment by mahmoud** [comment]
Very sorry about that. I believe I've identified the problem and will have a fix tonight (cc @markrwilliams).

**Comment by mt** [comment]
Thanks. Appreciate it.

**Comment by mahmoud** [comment]
Yeah, there was a silly little typo there that's sorted now. If you've got a minute to give the new version a test, that'd be great, otherwise I'll just push a new version to PyPI tonight. Thanks for a great report!

**Comment by mt** [comment]
Thanks for the fix. Everything looks good.
