### ISSUE TITLE
os.rename called in fileutils breaks on Windows if directory exists

### ISSUE THREAD

**Issue by davidovich** [mahmoud/boltons#60]
This was seen in the pip-tools code that is vendoring the AtomicSaver code from boltons.

https://github.com/nvie/pip-tools/pull/322

in essence, the os.rename cannot be implemented atomically on Windows, but the current code breaks if exercised. (see the issue in pip-tools). 

I will make a PR here as suggested by https://github.com/nvie

**Comment by mahmoud** [comment]
Oh, nice! Thank you for the report. This was something I had on my mind, but I got a bit caught up in research.

My back-of-mind plan was to implement MoveFileEx with ctypes, a la: http://stupidpythonideas.blogspot.com/2014/07/getting-atomic-writes-right.html

However, I was given pause by the revelation that MoveFileEx is not atomic: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240%28v=vs.85%29.aspx

That said, given these options versus the current behavior, I'm inclined to do the MoveFileEx ctypes. Time to dust off my Windows test machine :)

Let me know your thoughts.

**Comment by harvimt** [comment]
It looks like [`ReplaceFile`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365512%28v=vs.85%29.aspx) is the preferred way to do this on windows.

references:
https://msdn.microsoft.com/en-us/library/windows/desktop/hh802690%28v=vs.85%29.aspx#applications_updating_a_single_file_with_document-like_data
http://stackoverflow.com/questions/167414/is-an-atomic-file-rename-with-overwrite-possible-on-windows

**Comment by mahmoud** [comment]
Oh, good catch! Yes, upon closer reading of the blogspot post, that was the recommendation there as well, it was just emphasized weirdly. Thanks, @harvimt!

**Comment by mahmoud** [comment]
OK, I have a version that I consider final in master right now. It is tested working on both my Linux and Windows 7 machines. The code is here: https://github.com/mahmoud/boltons/blob/master/boltons/fileutils.py#L237

It uses ReplaceFile and adds `atomic_rename` and `replace` to the public API of `fileutils`. The semantics of `replace` are meant to be almost the same as 3.3+ `os.replace`. Except that according to our research ReplaceFile is better than MoveFileEx, so `fileutils.replace` may be superior.

Take a look and please, comment!

**Comment by mahmoud** [comment]
I'll leave this open a bit longer for discussion, but 16.1.0 is [now up on PyPI](https://pypi.python.org/pypi/boltons/16.1.0).

**Comment by davidovich** [comment]
This is fixed as of 16.1.0. 
Thanks for the better implementation.

**Comment by mahmoud** [comment]
I made one last tweak (225d98f) and I think we're good. Thanks again everyone!
