### ISSUE TITLE
Cached property

### ISSUE THREAD

**Issue by kdeldycke** [mahmoud/boltons#66]
I'm currently using [`cached-property`](https://pypi.python.org/pypi/cached-property) alongside `boltons` and I feel like `cached-property` features can be emulated with `boltons.cacheutils`.

Is this under the scope of `boltons`? Should we add some utils to support this feature in `boltons`?

**Comment by mahmoud** [comment]
I agree that that sort of functionality is a decent fit for cacheutils, and I have done a few specific implementations of the pattern so looking at a bolton makes sense. That said, I don't think there's anything in particular already in cacheutils that would enable it, so it's not the lowest-hanging fruit.

Is there something specific that you'd like to see in a new cached property API/implementation?

Thanks for bringing it up though, this is definitely something that comes up regularly!

**Comment by kdeldycke** [comment]
Thanks for the feedback. The way I cache properties is dead simple, stupid. So I have no particular requirement.

As you said it's quite a common pattern. Just implement a minimal working cached properties based on your needs. We'll iterate from there depending on real use-cases.

**Comment by mahmoud** [comment]
Hey @kdeldycke thanks for your patience. Have a look at [the new cachedproperty](https://github.com/mahmoud/boltons/blob/c74252986b1fbf89d651f1156127c4077d3aa3ef/boltons/cacheutils.py#L621). It takes the standard approach I've used in a couple of projects. There may be some niceties worth adding, but this one is the one that works for me!

**Comment by kdeldycke** [comment]
The new `cachedproperty()` is nice! That's exactly what I was looking for. I'll try it in the next couple of days. Let's close the issue for now. I'll re-open this one or a new one if I stumble upon any issue.

Thanks @mahmoud ! :)

**Comment by mahmoud** [comment]
Great! Planning to do a release this week.
