### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by dszmaj** [mahmoud/boltons#67]
Hey,

thanks for very useful package :)

Have you considered Python 3.5 support? Should I expect some unpredicted behaviour?

Best  #regards,
Dominik Szmaj

**Comment by harvimt** [comment]
The tests are running on 3.5, https://github.com/mahmoud/boltons/blob/master/.travis.yml#L8

And the tests are [passing](https://travis-ci.org/mahmoud/boltons), so you should be good.

And 3.5 is listed as being supported in the trove [specifiers](https://github.com/mahmoud/boltons/blob/master/setup.py#L42)

Actually why do you think 3.5 isn't supported?

**Comment by mahmoud** [comment]
I think you're good to go on Python 3.5, Dominik! Any unexpected behavior should be reported right here on the issue tracker. :)

**Comment by dszmaj** [comment]
@harvimt because i've read that ;)

> Boltons is tested against Python 2.6, 2.7, 3.4, and PyPy.
