### ISSUE TITLE
Add possibility to use cacheutils's decorator on class methods

### ISSUE THREAD

**Issue by grundic** [mahmoud/boltons#70]
Hi, great module first of all!
Right now I have to use [cachetools](https://github.com/tkem/cachetools) module, which provides `cachedmethod` decorator for using with class/instance methods.

Would it be possible to implement same for `cached` decorator so it would be possible to run something like:
```python
class Example(object):
    def __init__(self):
        self._cache = LRU()

    @cached(operator.attrgetter('_cache'))
    def heavy_func(self):
        print('Called')
        return 100500

instance = Example()
for _ in range(20):
    instance.heavy_func()  # should print `Called` just once
```

Ideally I would prefer single decorator for generic functions and for class methods, but if it's not possible it could be implemented with two different ones.

**Comment by mahmoud** [comment]
Thank you, and yes, totally! Let me review your pull request over on #69.

**Comment by mahmoud** [comment]
This now exists, in the form of [cachedmethod](https://github.com/mahmoud/boltons/blob/c74252986b1fbf89d651f1156127c4077d3aa3ef/boltons/cacheutils.py#L586). Let me know how it works for you, @grundic!

**Comment by grundic** [comment]
@mahmoud, looks just awesome! Much cleaner interface and easy to use. Thank you very much!
Could you please tell when do you plane to release it on PyPI?

**Comment by mahmoud** [comment]
Glad you approve! I plan on releasing as soon as #75 is merged, so hopefully this week :)
