### ISSUE TITLE
socketutils error in master on OSX

### ISSUE THREAD

**Issue by kalefranz** [mahmoud/boltons#71]
I'm working on building conda packages for boltons through conda-forge.  The in-progress PR is https://github.com/conda-forge/staged-recipes/pull/560

Linux packages build just fine (and it looks like those are what's covered in your .travis.yml).  There is one error on OS X and a few on Windows.  I'll file the Windows ticket separately.

The OS X error is in `tests/test_socketutils.py:test_client_disconnecting` and the full error output is [here](https://travis-ci.org/conda-forge/staged-recipes/jobs/129146756#L615)

    __________________________ test_client_disconnecting ___________________________
        def test_client_disconnecting():
            def get_bs_pair():
                x, y = socket.socketpair()
                bx, by = BufferedSocket(x), BufferedSocket(y)
        
                # sanity check
                by.sendall(b'123')
                bx.recv_size(3) == b'123'
        
                return bx, by
        
            bx, by = get_bs_pair()
            assert bx.fileno() > 0
        
            bx.close()
            assert bx.getrecvbuffer() == b''
        
            try:
                bx.recv(1)
            except socket.error:
                pass
            else:
                assert False, 'expected socket.error on closed recv'
        
            assert bx.fileno() == -1
        
            by.buffer(b'123')
            assert by.getsendbuffer()
            try:
                by.flush()
            except socket.error:
                assert by.getsendbuffer() == b'123'
            else:
                assert False, 'expected socket.error broken pipe'
        
    >       by.shutdown(socket.SHUT_RDWR)
    ../work/tests/test_socketutils.py:137: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    self = <boltons.socketutils.BufferedSocket object at 0x102d1bd10>, how = 2
        def shutdown(self, how):
            """Convenience method which passes through to the wrapped socket's
                :meth:`~socket.shutdown`. Semantics vary by platform, so no
                special internal handling is done with the buffers. This
                method exists to facilitate the most common usage, wherein a
                full ``shutdown`` is followed by a
                :meth:`~BufferedSocket.close`. Developers requiring more
                support, please open `an issue`_.
        
                .. _an issue: https://github.com/mahmoud/boltons/issues
                """
            with self._recv_lock:
                with self._send_lock:
    >               self.sock.shutdown(how)
    E               error: [Errno 57] Socket is not connected
    ../work/boltons/socketutils.py:559: error

Wanted to file the issue to start. At some point I'll dig in on a PR if somebody else doesn't get to it first.

**Comment by mahmoud** [comment]
This one actually kind of surprised me. I guess socketpair on Mac OS isn't identical to Linux after all. Unless this is a difference between 2.7.11 and lower versions. I'll do some research!

**Comment by mahmoud** [comment]
This test should also be fixed to not fail on OS X. As a platform-independent abstraction, Python's socket module is more than a bit leaky, but I'll discuss this behavior with some other developers, maybe come up with an improved API soon.
