### ISSUE TITLE
Make it possible to reconstruct parsed tracebacks?

### ISSUE THREAD

**Issue by d33tah** [mahmoud/boltons#80]
The current ParsedException class isn't compatible with "traceback" module:

```
[15:25:23]>>> traceback.print_tb(tb)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/traceback.py", line 61, in print_tb
    f = tb.tb_frame
AttributeError: 'ParsedException' object has no attribute 'tb_frame'
```

Perhaps it would be a good idea to make it possible to recontruct tracebacks back to strings after manipulation?

**Comment by mahmoud** [comment]
The goal is to turn it back into a string, right? I agree that that should be possible. As to whether passing it to the traceback module is the right way, I don't think so. 

If you have constructed it from a string, maybe the easiest thing is to just store that string. No chance of mis-reconstructing it. If you have constructed it manually, then I can see some reconstruction logic as a method on ParsedException.

I can probably give it a go this week, butt would you like to take a stab at this? It's definitely a feature gap, so thanks for identifying the issue either way.

**Comment by d33tah** [comment]
> butt would you like to take a stab at this?

Sorry, can't give it a go yet. Basically by re-construction I mean that I would like to be able to remove some frames from the parsed TB and then print it out again.

**Comment by mahmoud** [comment]
Ah, that makes sense. OK. I'll have a shot at it asap.

**Comment by d33tah** [comment]
@mahmoud: it's not a priority, just would-be-nice-to-have ;)

**Comment by mahmoud** [comment]
This was actually a lot easier than expected, so there is now code to do this. If you'd like to take it for a spin first, that'd be good, otherwise I'll be releasing it shortly.

**Comment by mahmoud** [comment]
This feature is in boltons 16.4.0! [Changelog is here](https://github.com/mahmoud/boltons/blob/master/CHANGELOG.md#1640). Just `pip install --upgrade boltons` and you'll be off and reconstructing. Let me know if you have any other issues.

**Comment by d33tah** [comment]
Yay!
