### ISSUE TITLE
Make it possible to use single cache for different methods

### ISSUE THREAD

**Issue by grundic** [mahmoud/boltons#83]
Would it be possible to implement cache separation of different methods with same signature for `cachedmethod` decorator? Here is small example with use of `boltons` and `cachetools`:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import operator
from boltons import cacheutils
import cachetools


class BoltonsCalculator(object):
    def __init__(self):
        self.cache = cacheutils.LRU()

    @cacheutils.cachedmethod('cache')
    def square(self, number):
        print("Calculating square of {}".format(number))
        return number * number

    @cacheutils.cachedmethod('cache')
    def cube(self, number):
        print("Calculating cube of {}".format(number))
        return number * number * number


class CachetoolsCalculator(object):
    def __init__(self):
        self.cache = cachetools.LRUCache(128)

    @cachetools.cachedmethod(operator.attrgetter('cache'))
    def square(self, number):
        print("Calculating square of {}".format(number))
        return number * number

    @cachetools.cachedmethod(operator.attrgetter('cache'))
    def cube(self, number):
        print("Calculating cube of {}".format(number))
        return number * number * number


if __name__ == '__main__':
    boltons_calc = BoltonsCalculator()
    print(boltons_calc.square(2))
    print(boltons_calc.square(2))
    print(boltons_calc.cube(2))

    print('-' * 80)

    cachetools_calc = CachetoolsCalculator()
    print(cachetools_calc.square(2))
    print(cachetools_calc.square(2))
    print(cachetools_calc.cube(2))

```

Here is output:
```bash
Calculating square of 2
4
4
4 <== I expect to get 8 here
--------------------------------------------------------------------------------
Calculating square of 2
4
4
Calculating cube of 2
8

Process finished with exit code 0

```

As you can see, third print gives us *4*, though I expect to get *8*.
Maybe [this](https://github.com/tkem/cachetools/blob/master/cachetools/__init__.py#L89) could help you better understand how this is implemented in `cachetools`.

**Comment by mahmoud** [comment]
Certainly possible! I'll run it past a couple other contributors and see what everyone thinks. Shouldn't be too much of a problem. Also, cachetools looks like a neat package, but I think the implementation will look a bit different (while having the same effect) :)

**Comment by grundic** [comment]
@mahmoud, thank you for your answer!
The implementation details is absolutely up to you, I've added a link to cachetools just to make my request more clear.

Personally I don't need this feature, but I think it would be nice to have: make usual functions (not bound methods) to follow same behaviour.

**Comment by mahmoud** [comment]
Hey @grundic! I updated `@cached` and `@cachedmethod` to behave as you describe. After a long think and some discussion, I agree that this would minimize surprising behavior for this particular corner of boltons. The critical change is the addition of the `scoped` argument to cached/cachedmethod. [The docs are already updated with the details](http://boltons.readthedocs.io/en/latest/cacheutils.html#boltons.cacheutils.cached), and I'm putting a release together as soon as I submit this comment.

**Comment by grundic** [comment]
@mahmoud sorry for late reply, as I was on vacation.

The change looks good for me, I've tested it with my code -- works good.
Agree, this `scope` parameter gives flexibility to the user to decide which behaviour he would like.

Thank you very much!
