### ISSUE TITLE
remap convert set to set of tuples

### ISSUE THREAD

**Issue by VicarEscaped** [mahmoud/boltons#84]
bolton's [remap](http://boltons.readthedocs.io/en/latest/iterutils.html#boltons.iterutils.remap) convert **sets** to **sets of tuples**, where first element of tuple is index in set, second is value.

```ipython
In [1]: !pip show boltons
---
Metadata-Version: 2.0
Name: boltons
Version: 16.5.0
...

In [2]: from boltons.iterutils import remap, default_enter

In [3]: def enter(path, key, value):
   ...:     ret = default_enter(path, key, value)
   ...:     return ret
   ...:

In [4]: d = {"set": {1, 2, 3}}

In [5]: remap(d, enter=enter)
Out[5]: {'set': {(0, 1), (1, 2), (2, 3)}}
```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
Windows 7

**Comment by mahmoud** [comment]
Good find! I've got a testcase and fix already committed and will be in the upcoming release. Interestingly this bug only affects sets and not frozensets, so as a workaround you can convert your set to a frozenset for the remap call.
