### ISSUE TITLE
Clarification of project allegance

### ISSUE THREAD

**Issue by fish2000** [mahmoud/boltons#88]
While the `boltons` project laudably disavows upfront any association with Michael Bolton, it is nonetheless silent on the matter of whether or not it has anything to do with [Ramsay Bolton](http://awoiaf.westeros.org/index.php/Ramsay_Snow) – which I would argue is a more pressingly pertinent disclosure.

![ramsay-bolton-face-sadistic-typical](https://cloud.githubusercontent.com/assets/378969/17768913/4c84d904-6504-11e6-9be1-c1ccb5dd15f9.jpg)

If at all possible, an explicit note in README.md about whether or not this project is at all related to Ramsay Bolton, one way or the other, would no doubt be appreciated by any and all users of this otherwise robust and circumspectly complete Python utility package. Thank you!

**Comment by mahmoud** [comment]
Closing as WILLNOTFIX, because clearly the dead have no allies. :)
